"use client";

import { motion, useReducedMotion } from "framer-motion";
import type { LucideIcon } from "lucide-react";

import {
  Activity,
  BadgeDollarSign,
  BarChart3,
  CircleDollarSign,
  Eye,
  FileText,
  MousePointerClick,
  Percent,
  Target,
  TrendingUp,
  UserRoundCheck,
  Users,
  WalletCards,
} from "lucide-react";

/* =========================================================
   METRICS
========================================================= */

const metrics = [
  {
    number: "01",
    title: "Reach",
    question:
      "How many relevant people are being exposed to your campaigns?",
    icon: Users,
  },
  {
    number: "02",
    title: "Impressions",
    question:
      "How frequently are your advertisements being shown?",
    icon: Eye,
  },
  {
    number: "03",
    title: "Click-Through Rate",
    question:
      "Is your message strong enough to earn attention and interaction?",
    icon: MousePointerClick,
  },
  {
    number: "04",
    title: "Cost Per Click",
    question:
      "How efficiently are campaigns generating website visits?",
    icon: CircleDollarSign,
  },
  {
    number: "05",
    title: "Conversion Rate",
    question:
      "What proportion of visitors complete the desired action?",
    icon: Percent,
  },
  {
    number: "06",
    title: "Cost Per Lead",
    question:
      "How much does it cost to generate a lead?",
    icon: BadgeDollarSign,
  },
  {
    number: "07",
    title: "Cost Per Acquisition",
    question:
      "What does it cost to acquire the desired customer or conversion?",
    icon: WalletCards,
  },
  {
    number: "08",
    title: "Lead Quality",
    question:
      "Are campaigns producing people your business can realistically convert?",
    icon: UserRoundCheck,
  },
  {
    number: "09",
    title: "Conversion Value",
    question:
      "How much measurable value is being generated by campaign activity?",
    icon: TrendingUp,
  },
  {
    number: "10",
    title: "Return On Ad Spend",
    question:
      "Where revenue data is available, how much measurable return is being generated relative to advertising spend?",
    icon: BarChart3,
  },
];

/* =========================================================
   MAIN
========================================================= */

export default function PerformanceMetricsSection() {
  const reduceMotion = useReducedMotion();

  const ease = [0.22, 1, 0.36, 1] as const;

  return (
    <section
      id="performance-metrics"
      aria-labelledby="performance-metrics-heading"
      className="
        relative
        isolate
        overflow-hidden
        bg-[#FBFAF7]
        py-20
        sm:py-24
        lg:py-28
        xl:py-32
      "
    >
      {/* =====================================================
          BACKGROUND
      ===================================================== */}

      <div className="pointer-events-none absolute inset-0 -z-20 overflow-hidden">
        <div
          className="
            absolute
            inset-0
            bg-gradient-to-br
            from-[#FCFBF8]
            via-white
            to-[#F4F8FB]
          "
        />

        <div
          className="
            absolute
            left-[16%]
            top-[12%]
            h-[540px]
            w-[760px]
            rounded-full
            bg-[#EAF2F8]/50
            blur-[115px]
          "
        />

        <div
          className="
            absolute
            right-[8%]
            top-[8%]
            h-[440px]
            w-[540px]
            rounded-full
            bg-[#F2E8DB]/38
            blur-[130px]
          "
        />

        {/* LEFT RINGS */}

        <div
          className="
            absolute
            -left-[260px]
            -top-[150px]
            h-[520px]
            w-[520px]
            rounded-full
            border
            border-[#C7A579]/20
          "
        />

        <div
          className="
            absolute
            -left-[205px]
            -top-[95px]
            h-[410px]
            w-[410px]
            rounded-full
            border
            border-[#0B2A52]/[0.05]
          "
        />

        {/* RIGHT RINGS */}

        <div
          className="
            absolute
            -right-[270px]
            top-[50px]
            h-[540px]
            w-[540px]
            rounded-full
            border
            border-[#C7A579]/20
          "
        />

        <div
          className="
            absolute
            -right-[215px]
            top-[105px]
            h-[430px]
            w-[430px]
            rounded-full
            border
            border-[#0B2A52]/[0.05]
          "
        />
      </div>

      {/* =====================================================
          SIDE MICROCOPY
      ===================================================== */}

      <div
        className="
          pointer-events-none
          absolute
          left-[2.5%]
          top-[110px]
          hidden
          2xl:block
        "
      >
        <p
          className="
            text-[0.51rem]
            font-semibold
            uppercase
            leading-[1.9]
            tracking-[0.28em]
            text-[#7893AD]
          "
        >
          STRATEGY
          <br />
          MEDIA
          <br />
          MEASUREMENT
          <br />
          GROWTH
        </p>
      </div>

      <div
        className="
          pointer-events-none
          absolute
          right-[2.7%]
          top-[110px]
          hidden
          border-l
          border-[#B78858]/55
          pl-5
          2xl:block
        "
      >
        <p
          className="
            text-[0.51rem]
            font-semibold
            uppercase
            leading-[1.9]
            tracking-[0.28em]
            text-[#7893AD]
          "
        >
          BETTER
          <br />
          INSIGHTS
          <br />
          BRIGHTER
          <br />
          GROWTH
        </p>
      </div>

      {/* =====================================================
          CONTAINER
      ===================================================== */}

      <div
        className="
          relative
          z-10
          mx-auto
          w-full
          max-w-[1540px]
          px-5
          sm:px-8
          lg:px-10
          xl:px-12
        "
      >
        {/* =====================================================
            HEADER
        ===================================================== */}

        <div className="mx-auto max-w-[1080px] text-center">
          <motion.div
            initial={{
              opacity: 0,
              y: reduceMotion ? 0 : 14,
            }}
            whileInView={{
              opacity: 1,
              y: 0,
            }}
            viewport={{
              once: true,
              amount: 0.7,
            }}
            transition={{
              duration: reduceMotion ? 0 : 0.6,
              ease,
            }}
            className="
              flex
              items-center
              justify-center
              gap-4
            "
          >
            <span className="h-px w-10 bg-[#B67D49]" />

            <span
              className="
                text-[0.65rem]
                font-semibold
                uppercase
                tracking-[0.32em]
                text-[#335E87]
              "
            >
              What We Measure
            </span>

            <span className="h-px w-10 bg-[#B67D49]" />
          </motion.div>

          <motion.h2
            id="performance-metrics-heading"
            initial={{
              opacity: 0,
              y: reduceMotion ? 0 : 28,
            }}
            whileInView={{
              opacity: 1,
              y: 0,
            }}
            viewport={{
              once: true,
              amount: 0.5,
            }}
            transition={{
              duration: reduceMotion ? 0 : 0.8,
              delay: reduceMotion ? 0 : 0.05,
              ease,
            }}
            className="
              mt-5
              font-serif
              text-[2.3rem]
              font-medium
              leading-[1.03]
              tracking-[-0.045em]
              text-[#071F45]

              sm:text-[2.6rem]
              md:text-[2.95rem]
              lg:text-[3.1rem]
              xl:text-[3.35rem]
            "
          >
            Numbers Should Tell You What to{" "}
            <span
              className="
                font-normal
                italic
                text-[#A97743]
              "
            >
              Do Next.
            </span>
          </motion.h2>

          <motion.p
            initial={{
              opacity: 0,
              y: reduceMotion ? 0 : 18,
            }}
            whileInView={{
              opacity: 1,
              y: 0,
            }}
            viewport={{
              once: true,
              amount: 0.6,
            }}
            transition={{
              duration: reduceMotion ? 0 : 0.7,
              delay: reduceMotion ? 0 : 0.1,
              ease,
            }}
            className="
              mx-auto
              mt-4
              max-w-[820px]
              text-[0.98rem]
              leading-[1.6]
              text-[#455D75]
              sm:text-[1rem]
            "
          >
            Performance reporting should make advertising decisions clearer.
            Not more complicated.
          </motion.p>

          <motion.p
            initial={{
              opacity: 0,
            }}
            whileInView={{
              opacity: 1,
            }}
            viewport={{
              once: true,
            }}
            transition={{
              duration: reduceMotion ? 0 : 0.7,
              delay: reduceMotion ? 0 : 0.18,
            }}
            className="
              mt-2
              text-[0.78rem]
              font-medium
              text-[#193C62]
            "
          >
            Depending on your business and campaign objectives, we may monitor:
          </motion.p>
        </div>

        {/* =====================================================
            PERFORMANCE VISUAL

            IMPORTANT:
            NO SIDE CARD USES absolute / negative margin.
            THREE TRUE COLUMNS AT XL.
        ===================================================== */}

        <motion.div
          initial={{
            opacity: 0,
            y: reduceMotion ? 0 : 34,
            scale: reduceMotion ? 1 : 0.985,
          }}
          whileInView={{
            opacity: 1,
            y: 0,
            scale: 1,
          }}
          viewport={{
            once: true,
            amount: 0.15,
          }}
          transition={{
            duration: reduceMotion ? 0 : 0.9,
            delay: reduceMotion ? 0 : 0.12,
            ease,
          }}
          className="
            mx-auto
            mt-11
            max-w-[1420px]
          "
        >
          <div
            className="
              grid
              gap-5

              xl:grid-cols-[205px_minmax(0,1fr)_205px]
              xl:items-center

              2xl:grid-cols-[215px_minmax(0,1fr)_215px]
              2xl:gap-6
            "
          >
            {/* =================================================
                LEFT COLUMN — TOTAL SPEND
            ================================================= */}

            <div
              className="
                order-2
                grid
                sm:grid-cols-2

                xl:order-1
                xl:block
                xl:self-center
              "
            >
              <SideStatCard
                title="Total Spend"
                value="$14,680"
                change="↓ 16%"
                description="More efficient spend for stronger results."
                chart="bars"
                reduceMotion={reduceMotion}
              />
            </div>

            {/* =================================================
                CENTER — MAIN DASHBOARD
            ================================================= */}

            <div
              className="
                order-1
                min-w-0

                xl:order-2
              "
            >
              <div
                className="
                  overflow-hidden

                  rounded-[1.5rem]

                  border
                  border-[#244868]

                  bg-gradient-to-b
                  from-[#173B5D]
                  to-[#102D49]

                  p-[10px]

                  shadow-[0_30px_85px_rgba(11,42,82,0.21)]
                "
              >
                <div
                  className="
                    overflow-hidden
                    rounded-[1rem]
                    bg-[#F8F9FA]

                    lg:grid
                    lg:grid-cols-[145px_minmax(0,1fr)]
                  "
                >
                  {/* =============================================
                      DASHBOARD SIDEBAR
                  ============================================= */}

                  <aside
                    className="
                      hidden
                      bg-gradient-to-b
                      from-[#173858]
                      to-[#0D2945]
                      px-4
                      py-5
                      lg:block
                    "
                  >
                    <div
                      className="
                        flex
                        items-center
                        gap-2

                        border-b
                        border-white/10

                        pb-5
                      "
                    >
                      <div
                        className="
                          flex
                          h-8
                          w-8
                          items-center
                          justify-center
                          text-[#C4935E]
                        "
                      >
                        <TrendingUp
                          size={22}
                          strokeWidth={1.5}
                        />
                      </div>

                      <span
                        className="
                          font-serif
                          text-[0.95rem]
                          text-white
                        "
                      >
                        Sharp Rays
                      </span>
                    </div>

                    <div className="mt-5 space-y-1.5">
                      <NavItem
                        icon={Activity}
                        label="Overview"
                        active
                      />

                      <NavItem
                        icon={Target}
                        label="Campaigns"
                      />

                      <NavItem
                        icon={Users}
                        label="Audiences"
                      />

                      <NavItem
                        icon={BarChart3}
                        label="Analytics"
                      />

                      <NavItem
                        icon={UserRoundCheck}
                        label="Conversions"
                      />

                      <NavItem
                        icon={FileText}
                        label="Reports"
                      />
                    </div>
                  </aside>

                  {/* =============================================
                      DASHBOARD CONTENT
                  ============================================= */}

                  <div className="min-w-0 bg-[#F7F8F9] p-4 sm:p-5">
                    {/* HEADER */}

                    <div
                      className="
                        flex
                        flex-col
                        gap-4

                        sm:flex-row
                        sm:items-center
                        sm:justify-between
                      "
                    >
                      <div>
                        <h3
                          className="
                            text-[0.98rem]
                            font-semibold
                            text-[#0B2A52]
                          "
                        >
                          Performance Overview
                        </h3>

                        <p
                          className="
                            mt-0.5
                            text-[0.58rem]
                            text-[#6C7A88]
                          "
                        >
                          Turning data into smarter marketing decisions.
                        </p>
                      </div>

                      <div
                        className="
                          w-fit

                          rounded-md

                          border
                          border-[#DCE3E8]

                          bg-white

                          px-3
                          py-2

                          text-[0.48rem]
                          font-medium
                          text-[#506276]
                        "
                      >
                        Oct 1, 2024 – Oct 31, 2024
                      </div>
                    </div>

                    {/* =============================================
                        KPI ROW
                    ============================================= */}

                    <div
                      className="
                        mt-4
                        grid
                        gap-3

                        sm:grid-cols-2
                        2xl:grid-cols-4
                      "
                    >
                      <DashboardMetric
                        title="Reach"
                        value="482,731"
                        change="↑ 12%"
                        icon={Users}
                      />

                      <DashboardMetric
                        title="Impressions"
                        value="1,926,305"
                        change="↑ 18%"
                        icon={Eye}
                      />

                      <DashboardMetric
                        title="CTR"
                        value="2.4%"
                        change="↑ 0.6%"
                        icon={MousePointerClick}
                      />

                      <DashboardMetric
                        title="Cost Per Click"
                        value="$0.78"
                        change="↓ 14%"
                        icon={CircleDollarSign}
                      />
                    </div>

                    {/* =============================================
                        LOWER ANALYTICS
                    ============================================= */}

                    <div
                      className="
                        mt-3
                        grid
                        gap-3

                        lg:grid-cols-2
                      "
                    >
                      {/* CONVERSIONS */}

                      <div
                        className="
                          min-w-0
                          overflow-hidden

                          rounded-[0.75rem]

                          border
                          border-[#E0E5E9]

                          bg-white

                          p-4
                        "
                      >
                        <p
                          className="
                            text-[0.54rem]
                            font-semibold
                            text-[#41566B]
                          "
                        >
                          Conversions
                        </p>

                        <div
                          className="
                            mt-1
                            flex
                            items-end
                            gap-3
                          "
                        >
                          <span
                            className="
                              text-[1.15rem]
                              font-semibold
                              text-[#0B2A52]
                            "
                          >
                            1,842
                          </span>

                          <span
                            className="
                              pb-0.5
                              text-[0.52rem]
                              font-semibold
                              text-[#159665]
                            "
                          >
                            ↑ 28%
                          </span>
                        </div>

                        <LineChart />
                      </div>

                      {/* CONVERSION VALUE */}

                      <div
                        className="
                          min-w-0
                          overflow-hidden

                          rounded-[0.75rem]

                          border
                          border-[#E0E5E9]

                          bg-white

                          p-4
                        "
                      >
                        <p
                          className="
                            text-[0.54rem]
                            font-semibold
                            text-[#41566B]
                          "
                        >
                          Conversion Value
                        </p>

                        <div
                          className="
                            mt-1
                            flex
                            items-end
                            gap-3
                          "
                        >
                          <span
                            className="
                              text-[1.15rem]
                              font-semibold
                              text-[#0B2A52]
                            "
                          >
                            $84,320
                          </span>

                          <span
                            className="
                              pb-0.5
                              text-[0.52rem]
                              font-semibold
                              text-[#159665]
                            "
                          >
                            ↑ 32%
                          </span>
                        </div>

                        <ValueBars />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* =================================================
                RIGHT COLUMN — INSIGHT RAIL

                Separate grid column.
                Cannot cover dashboard.
            ================================================= */}

            <div
              className="
                order-3
                grid
                gap-5

                sm:grid-cols-2

                xl:grid-cols-1
                xl:self-center
              "
            >
              <SideStatCard
                title="Return On Ad Spend"
                value="5.7x"
                change="↑ 34%"
                description="Higher returns through smarter optimization."
                chart="line"
                reduceMotion={reduceMotion}
                delay={0.08}
              />

              <SideStatCard
                title="New Leads"
                value="1,842"
                change="↑ 28%"
                description="A steady pipeline of qualified opportunities."
                chart="bars"
                reduceMotion={reduceMotion}
                delay={0.16}
              />
            </div>
          </div>
        </motion.div>

        {/* =====================================================
            10 METRIC CARDS
        ===================================================== */}

        <div
          className="
            relative
            z-20

            mx-auto
            mt-7

            grid
            max-w-[1400px]
            gap-3

            sm:grid-cols-2
            lg:grid-cols-5
          "
        >
          {metrics.map((metric, index) => {
            const Icon = metric.icon;

            return (
              <motion.article
                key={metric.number}
                initial={{
                  opacity: 0,
                  y: reduceMotion ? 0 : 22,
                }}
                whileInView={{
                  opacity: 1,
                  y: 0,
                }}
                viewport={{
                  once: true,
                  amount: 0.3,
                }}
                transition={{
                  duration: reduceMotion ? 0 : 0.55,
                  delay:
                    reduceMotion
                      ? 0
                      : (index % 5) * 0.05,
                  ease,
                }}
                whileHover={
                  reduceMotion
                    ? undefined
                    : {
                        y: -4,
                      }
                }
                className="
                  group

                  min-h-[132px]

                  rounded-[0.85rem]

                  border
                  border-white

                  bg-white/88

                  p-4

                  shadow-[0_10px_30px_rgba(11,42,82,0.065)]

                  backdrop-blur-xl

                  transition-all
                  duration-300

                  hover:border-[#B9D1E2]
                  hover:shadow-[0_16px_40px_rgba(11,42,82,0.10)]
                "
              >
                <div
                  className="
                    flex
                    items-start
                    gap-3
                  "
                >
                  <div
                    className="
                      flex
                      h-8
                      w-8
                      shrink-0
                      items-center
                      justify-center
                      text-[#0B3A6D]
                    "
                  >
                    <Icon
                      size={20}
                      strokeWidth={1.55}
                    />
                  </div>

                  <div>
                    <h3
                      className="
                        text-[0.72rem]
                        font-semibold
                        leading-[1.35]
                        text-[#0B2A52]
                      "
                    >
                      {metric.title}
                    </h3>

                    <p
                      className="
                        mt-2
                        text-[0.66rem]
                        leading-[1.5]
                        text-[#536A80]
                      "
                    >
                      {metric.question}
                    </p>
                  </div>
                </div>
              </motion.article>
            );
          })}
        </div>

        {/* =====================================================
            IMPORTANT PART
        ===================================================== */}

        <motion.div
          initial={{
            opacity: 0,
            y: reduceMotion ? 0 : 28,
          }}
          whileInView={{
            opacity: 1,
            y: 0,
          }}
          viewport={{
            once: true,
            amount: 0.35,
          }}
          transition={{
            duration: reduceMotion ? 0 : 0.8,
            ease,
          }}
          className="
            mx-auto
            mt-6
            max-w-[1400px]

            overflow-hidden

            rounded-[1.3rem]

            border
            border-[#D6E2EB]

            bg-gradient-to-r
            from-[#EDF5FB]
            via-[#F8FAFC]
            to-[#EEF5FA]

            px-6
            py-7

            shadow-[0_14px_40px_rgba(11,42,82,0.05)]

            sm:px-8
            lg:px-10
          "
        >
          <div
            className="
              grid
              gap-8

              lg:grid-cols-[1.05fr_1px_0.95fr_auto]
              lg:items-center
            "
          >
            {/* LEFT */}

            <div>
              <div
                className="
                  flex
                  items-center
                  gap-4
                "
              >
                <span className="h-px w-10 bg-[#B67D49]" />

                <span
                  className="
                    text-[0.57rem]
                    font-semibold
                    uppercase
                    tracking-[0.28em]
                    text-[#355E87]
                  "
                >
                  The Important Part
                </span>
              </div>

              <h3
                className="
                  mt-4

                  font-serif
                  text-[1.75rem]
                  font-medium
                  leading-[1.15]
                  tracking-[-0.035em]

                  text-[#071F45]

                  sm:text-[2rem]
                  lg:text-[2.15rem]
                "
              >
                A lower cost is{" "}
                <span
                  className="
                    font-normal
                    italic
                    text-[#A97743]
                  "
                >
                  not automatically better.
                </span>
              </h3>
            </div>

            {/* DIVIDER */}

            <div
              className="
                hidden
                h-[72px]
                w-px
                bg-[#C6D1DA]
                lg:block
              "
            />

            {/* COPY */}

            <div>
              <p
                className="
                  max-w-[520px]
                  text-[0.8rem]
                  leading-[1.65]
                  text-[#536A80]
                "
              >
                A cheap lead that never becomes a customer may be less valuable
                than a more expensive lead with stronger buying intent.
              </p>

              <p
                className="
                  mt-3
                  text-[0.8rem]
                  font-semibold
                  leading-[1.6]
                  text-[#0B2A52]
                "
              >
                We optimize around business value, not impressive-looking
                dashboard numbers.
              </p>
            </div>

            {/* MICRO */}

            <div
              className="
                hidden
                items-center
                gap-4

                border-l
                border-[#C7D3DD]

                pl-7

                xl:flex
              "
            >
              <div
                className="
                  flex
                  items-end
                  gap-1
                "
              >
                {[18, 30, 42, 58].map((height) => (
                  <span
                    key={height}
                    style={{
                      height,
                    }}
                    className="
                      w-[5px]
                      bg-gradient-to-t
                      from-[#B67D49]
                      to-[#D7B690]
                    "
                  />
                ))}
              </div>

              <p
                className="
                  text-[0.49rem]
                  font-semibold
                  uppercase
                  leading-[1.8]
                  tracking-[0.25em]
                  text-[#7490AA]
                "
              >
                REAL DATA
                <br />
                REAL DECISIONS
                <br />
                REAL GROWTH
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}

/* =========================================================
   SIDE STAT CARD
========================================================= */

function SideStatCard({
  title,
  value,
  change,
  description,
  chart,
  reduceMotion,
  delay = 0,
}: {
  title: string;
  value: string;
  change: string;
  description: string;
  chart: "line" | "bars";
  reduceMotion: boolean | null;
  delay?: number;
}) {
  return (
    <motion.div
      initial={{
        opacity: 0,
        y: reduceMotion ? 0 : 18,
      }}
      whileInView={{
        opacity: 1,
        y: 0,
      }}
      viewport={{
        once: true,
        amount: 0.4,
      }}
      transition={{
        duration: reduceMotion ? 0 : 0.65,
        delay: reduceMotion ? 0 : delay,
        ease: [0.22, 1, 0.36, 1],
      }}
      className="
        w-full

        overflow-hidden

        rounded-[1.25rem]

        border
        border-white

        bg-white/95

        p-5

        shadow-[0_18px_48px_rgba(11,42,82,0.10)]

        backdrop-blur-xl

        xl:min-h-[220px]
      "
    >
      {/* TOP */}

      <div
        className="
          flex
          items-start
          justify-between
          gap-3
        "
      >
        <span
          className="
            text-[0.59rem]
            font-semibold
            leading-[1.4]
            text-[#173A5E]
          "
        >
          {title}
        </span>

        <span
          className="
            text-[0.7rem]
            tracking-[0.14em]
            text-[#73869A]
          "
        >
          •••
        </span>
      </div>

      {/* VALUE */}

      <div
        className="
          mt-5
          flex
          flex-wrap
          items-end
          gap-x-3
          gap-y-1
        "
      >
        <span
          className="
            font-serif
            text-[1.9rem]
            font-semibold
            leading-none
            tracking-[-0.035em]
            text-[#071F45]

            2xl:text-[2rem]
          "
        >
          {value}
        </span>

        <span
          className="
            mb-0.5
            text-[0.55rem]
            font-semibold
            text-[#159665]
          "
        >
          {change}
        </span>
      </div>

      {/* GRAPH */}

      <div className="mt-5">
        {chart === "line" ? (
          <MiniLine />
        ) : (
          <MiniBars />
        )}
      </div>

      {/* DESCRIPTION */}

      <p
        className="
          mt-4
          text-[0.61rem]
          leading-[1.5]
          text-[#64788B]
        "
      >
        {description}
      </p>
    </motion.div>
  );
}

/* =========================================================
   DASHBOARD METRIC
========================================================= */

function DashboardMetric({
  title,
  value,
  change,
  icon: Icon,
}: {
  title: string;
  value: string;
  change: string;
  icon: LucideIcon;
}) {
  return (
    <div
      className="
        rounded-[0.65rem]

        border
        border-[#E1E6EA]

        bg-white

        p-3

        shadow-[0_4px_12px_rgba(11,42,82,0.025)]
      "
    >
      <div
        className="
          flex
          items-start
          justify-between
          gap-2
        "
      >
        <div className="min-w-0">
          <p
            className="
              text-[0.46rem]
              font-semibold
              text-[#445A70]
            "
          >
            {title}
          </p>

          <p
            className="
              mt-1
              truncate
              text-[0.91rem]
              font-semibold
              text-[#0B2A52]
            "
          >
            {value}
          </p>
        </div>

        <Icon
          size={15}
          strokeWidth={1.6}
          className="
            shrink-0
            text-[#0B3E70]
          "
        />
      </div>

      <p
        className="
          mt-1
          text-[0.47rem]
          font-semibold
          text-[#159665]
        "
      >
        {change}
      </p>
    </div>
  );
}

/* =========================================================
   NAV ITEM
========================================================= */

function NavItem({
  icon: Icon,
  label,
  active = false,
}: {
  icon: LucideIcon;
  label: string;
  active?: boolean;
}) {
  return (
    <div
      className={`
        flex
        items-center
        gap-2.5

        rounded-md

        px-3
        py-2

        text-[0.53rem]

        transition-colors

        ${
          active
            ? `
              bg-white/10
              text-[#E6C89E]
            `
            : `
              text-white/65
            `
        }
      `}
    >
      <Icon
        size={13}
        strokeWidth={1.6}
      />

      <span>{label}</span>
    </div>
  );
}

/* =========================================================
   LINE CHART
========================================================= */

function LineChart() {
  return (
    <div className="relative mt-4 h-[118px]">
      <div
        className="
          absolute
          inset-0

          opacity-60

          [background-image:linear-gradient(to_right,#0B2A5208_1px,transparent_1px),linear-gradient(to_bottom,#0B2A5208_1px,transparent_1px)]
          [background-size:20%_25%]
        "
      />

      <svg
        viewBox="0 0 400 120"
        preserveAspectRatio="none"
        className="
          absolute
          inset-0
          h-full
          w-full
        "
        aria-hidden="true"
      >
        <defs>
          <linearGradient
            id="conversionFill"
            x1="0"
            y1="0"
            x2="0"
            y2="1"
          >
            <stop
              offset="0%"
              stopColor="#4B92D1"
              stopOpacity="0.26"
            />

            <stop
              offset="100%"
              stopColor="#4B92D1"
              stopOpacity="0"
            />
          </linearGradient>
        </defs>

        <path
          d="
            M 0 100
            L 24 91
            L 48 86
            L 72 88
            L 96 77
            L 120 82
            L 144 74
            L 168 62
            L 192 72
            L 216 65
            L 240 67
            L 264 48
            L 288 61
            L 312 48
            L 336 38
            L 360 45
            L 384 28
            L 400 20
            L 400 120
            L 0 120
            Z
          "
          fill="url(#conversionFill)"
        />

        <path
          d="
            M 0 100
            L 24 91
            L 48 86
            L 72 88
            L 96 77
            L 120 82
            L 144 74
            L 168 62
            L 192 72
            L 216 65
            L 240 67
            L 264 48
            L 288 61
            L 312 48
            L 336 38
            L 360 45
            L 384 28
            L 400 20
          "
          fill="none"
          stroke="#1E73C9"
          strokeWidth="2.2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    </div>
  );
}

/* =========================================================
   VALUE BARS
========================================================= */

function ValueBars() {
  const values = [
    20, 24, 30, 35, 42, 39, 47, 51, 58,
    55, 63, 66, 74, 70, 82, 90, 96,
  ];

  return (
    <div
      className="
        mt-4
        flex
        h-[118px]
        items-end
        gap-[5px]

        border-b
        border-[#DDE4E9]

        pb-1
      "
    >
      {values.map((height, index) => (
        <motion.span
          key={index}
          initial={{
            height: 0,
          }}
          whileInView={{
            height: `${height}%`,
          }}
          viewport={{
            once: true,
          }}
          transition={{
            duration: 0.55,
            delay: index * 0.025,
          }}
          className="
            flex-1
            bg-gradient-to-t
            from-[#4E96D1]
            to-[#99C9EC]
          "
        />
      ))}
    </div>
  );
}

/* =========================================================
   SIDE CARD BARS
========================================================= */

function MiniBars() {
  const bars = [
    28, 40, 51, 64, 78, 55, 44,
    36, 58, 49, 38, 39, 52, 72, 88,
  ];

  return (
    <div
      className="
        flex
        h-[58px]
        items-end
        gap-[4px]
      "
    >
      {bars.map((height, index) => (
        <motion.span
          key={index}
          initial={{
            height: 0,
          }}
          whileInView={{
            height: `${height}%`,
          }}
          viewport={{
            once: true,
          }}
          transition={{
            duration: 0.45,
            delay: index * 0.025,
          }}
          className="
            flex-1
            bg-gradient-to-t
            from-[#96AFC5]
            to-[#D8E4ED]
          "
        />
      ))}
    </div>
  );
}

/* =========================================================
   SIDE CARD LINE
========================================================= */

function MiniLine() {
  return (
    <svg
      viewBox="0 0 170 60"
      preserveAspectRatio="none"
      aria-hidden="true"
      className="
        h-[60px]
        w-full
      "
    >
      <defs>
        <linearGradient
          id="roasArea"
          x1="0"
          y1="0"
          x2="0"
          y2="1"
        >
          <stop
            offset="0%"
            stopColor="#B88856"
            stopOpacity="0.28"
          />

          <stop
            offset="100%"
            stopColor="#B88856"
            stopOpacity="0"
          />
        </linearGradient>
      </defs>

      <path
        d="
          M0 48
          L12 44
          L24 36
          L36 41
          L48 32
          L60 37
          L72 27
          L85 33
          L99 27
          L112 30
          L126 21
          L140 20
          L153 13
          L164 16
          L170 7
          L170 60
          L0 60
          Z
        "
        fill="url(#roasArea)"
      />

      <path
        d="
          M0 48
          L12 44
          L24 36
          L36 41
          L48 32
          L60 37
          L72 27
          L85 33
          L99 27
          L112 30
          L126 21
          L140 20
          L153 13
          L164 16
          L170 7
        "
        fill="none"
        stroke="#B17A42"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}